### ISSUE TITLE
Not able to configure Lovelace

### ISSUE THREAD

**Issue by MaikolplaysLive** [dollop80/homeassistant-xiaomi-water-purifier-yunmi#1]
I´m following the instructions but are not able to see any of the sensors in lovelace. the only option created is a group named "group.water_purifier"  which has a status of unknown....

shouldn´t I be able to select all the sensors listed under entities in groups.yaml (and be able to use them in an entities panel in lovelace )?

entities:
      - sensor.tap_water
      - sensor.filtered_water
      - sensor.pp_cotton_filter
      - sensor.front_active_carbon_filter
      - sensor.ro_filter
      - sensor.rear_active_carbon_filter

thanks for any advice in advance !!

**Comment by dollop80** [comment]
> shouldn´t I be able to select all the sensors listed under entities in groups.yaml (and be able to use them in an entities panel in lovelace )?

Yes. You are right. But your entities do not seem to me correct.
- Use latest Home Assistant (at least Home Assistant 2021.1.5)
- Please kindly check all the installation steps.
- Double check the groups.yaml file and configuration.yaml (this is a screenshot of my groups.yaml)
![image](https://user-images.githubusercontent.com/11781188/107884496-05069c80-6efe-11eb-9319-67b10b0a9636.png)
- After server reboot you'll be able to find in configuration->entities (search "water") the sensors
![image](https://user-images.githubusercontent.com/11781188/107884603-95dd7800-6efe-11eb-919e-9e7a63e8ba86.png)
and to check the water purifier's status
![image](https://user-images.githubusercontent.com/11781188/107884632-b574a080-6efe-11eb-8cf1-6d9a499e5b47.png)
